// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["VITE_SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["VITE_SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Running in demo mode.`;
    console.warn(`[Supabase] ${message}`);

    // Minimal mock implementation to let the app run in read-only/demo mode.
    class MockBuilder {
      then(resolve: (v: unknown) => void) {
        // Resolve with an object similar to Supabase responses
        resolve({ data: [], error: null });
      }
      select() {
        return this;
      }
      order() {
        return this;
      }
      gte() {
        return this;
      }
      lte() {
        return this;
      }
      insert() {
        return Promise.resolve({ data: null, error: null });
      }
      delete() {
        return Promise.resolve({ data: null, error: null });
      }
      update() {
        return Promise.resolve({ data: null, error: null });
      }
      upsert() {
        return Promise.resolve({ data: null, error: null });
      }
    }

    const mockClient: any = {
      from: () => new MockBuilder(),
      auth: {
        async getSession() {
          return { data: { session: null } };
        },
        onAuthStateChange(_cb: any) {
          return { subscription: { unsubscribe() {} } };
        },
        async signInWithPassword() {
          return { error: new Error("Auth unavailable in demo mode") };
        },
        async signUp() {
          return { error: new Error("Auth unavailable in demo mode") };
        },
      },
    };

    return mockClient as unknown as ReturnType<typeof createClient>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
